[package]
name = "compat"
version = "0.1.0"
authors = ["Aiden McClelland <me@drbonez.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
serde = { version="1.0.118", features=["derive", "rc"] }
serde_yaml = "0.8.17"
embassy-os = { path="../appmgr", default-features=false }
emver = { version = "0.1.2", features = ["serde"] }
futures = "0.3.8"
rust-argon2 = "0.8.3"
rand = "0.8.4"
tokio = { version = "1.8.1", features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["io-util", "sync"] }
anyhow = "1.0.40"
log = "0.4.11"
itertools = "0.10.0"
regex = "1.4.2"
